AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: A SCIM2 service accessible through a public gateway

Globals:
  Function:
    Handler: cli.lambda_handler
    MemorySize: 256
    Timeout: 600
    Runtime: python3.10
    Environment:
      Variables:
        Log_Level: INFO

Resources:
  Scim2ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              
  Scim2ServiceHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "./src/"
      Description: "ScimService"
      Handler: lambda.lambda_handler
      Events:
        ScimProxy:
          Type: Api
          Properties:
            RestApiId: !Ref Scim2ApiGateway
            Path: /{proxy+}  # Catches all paths 
            Method: ANY      # Supports all HTTP methods
